### ISSUE TITLE
page erreur.php ?

### ISSUE THREAD

**Issue by totaldebrid** [kpslcorp/janembart#1]
Bonjour jai une page erreur.php quand je veut ajouter un site et sur toute les page externe du site genre  urldusite/3.1-debrideur.html jai aussi une page  erreur.php ? aussi sur les page  urldusite/index-amp.html  et autre  pouvez vous m'aidez svp merci

**Comment by kpslcorp** [comment]
Bonjour,
Je suis quasi-sur qu'il s'agit d'un problème de .htaccess mal paramétré
On voit ça en MP ;)

**Comment by totaldebrid** [comment]
Bonjour j'ai mis le fichier htaccess  en piece jointe a vrais dire je les pas retoucher il est t'elle que j'ai vu nul par qu'il fallais le paramettrer mais je ne serais pas le faire non plus car je suis novice merci pour vos réponse  rapide
[.htaccess.zip](https://github.com/kpslcorp/Janembart/files/8601574/default.htaccess.zip)

**Comment by totaldebrid** [comment]
Problème résolut c’était bien le fichier htaccess merci pour la rapidité de la réponse  

merci pour tous  ;)

**Comment by kpslcorp** [comment]
Merci à vous ;)
